#!/usr/bin/env python3
import os
import yaml

YAML_FILE = "../nodes.yaml"
SSH_CONFIG = os.path.expanduser("~/.ssh/config")

BEGIN_MARK = "# --- AUTOGENERATED rpic cluster --- BEGIN"
END_MARK = "# --- AUTOGENERATED rpic cluster --- END"


def load_yaml(path):
    with open(path) as f:
        return yaml.safe_load(f)


def build_block(config):
    user = config["defaults"]["user"]
    key = os.path.expanduser(config["defaults"]["key"])
    nodes = config["nodes"]

    lines = [BEGIN_MARK]
    lines.append(f"Host rpic-*")
    lines.append(f"  User {user}")
    lines.append(f"  IdentityFile {key}")
    lines.append("")

    for name, ip in nodes.items():
        lines.append(f"Host {name}")
        lines.append(f"  HostName {ip}")
        lines.append("")

    lines.append(END_MARK)
    return [l + "\n" for l in lines]


def update_config():
    cfg = load_yaml(YAML_FILE)
    new_block = build_block(cfg)

    if os.path.exists(SSH_CONFIG):
        with open(SSH_CONFIG) as f:
            lines = f.readlines()
    else:
        lines = []

    out_lines = []
    inside_block = False
    for line in lines:
        if line.strip() == BEGIN_MARK:
            inside_block = True
            continue
        if line.strip() == END_MARK:
            inside_block = False
            continue
        if not inside_block:
            out_lines.append(line)

    out_lines.extend(new_block)

    with open(SSH_CONFIG, "w") as f:
        f.writelines(out_lines)

    print(f"Synced {SSH_CONFIG} with {len(cfg['nodes'])} hosts from {YAML_FILE}")


if __name__ == "__main__":
    update_config()
