- hosts: workers
  become: true
  tasks:
    - name: Read token from server
      slurp:
        src: /var/lib/rancher/k3s/server/node-token
      delegate_to: "{{ groups['server'][0] }}"
      run_once: true
      register: node_token   

    - name: Set token fact
      set_fact:
        k3s_token: "{{ node_token['content'] | b64decode | trim }}"

    - name: Install K3s worker
      shell: >
        curl -sfL https://get.k3s.io |
        K3S_URL="https://{{ hostvars[groups['server'][0]].ansible_host }}:6443"
        K3S_TOKEN="{{ k3s_token }}"
        sh -
      args:
        creates: /usr/local/bin/k3s
